# Generated by Django 4.1.3 on 2023-03-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
