# Generated by Django 4.1.3 on 2023-02-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userbase",
            old_name="addrress_2",
            new_name="address_2",
        ),
    ]
