# Generated by Django 4.1.3 on 2023-02-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_addrress_2_userbase_address_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbase",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
