# Generated by Django 4.1.3 on 2023-02-18 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userbase_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userbase",
            name="address_1",
        ),
        migrations.RemoveField(
            model_name="userbase",
            name="address_2",
        ),
        migrations.RemoveField(
            model_name="userbase",
            name="city",
        ),
        migrations.RemoveField(
            model_name="userbase",
            name="country",
        ),
        migrations.RemoveField(
            model_name="userbase",
            name="name",
        ),
        migrations.RemoveField(
            model_name="userbase",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="userbase",
            name="postcode",
        ),
        migrations.RemoveField(
            model_name="userbase",
            name="surname",
        ),
        migrations.CreateModel(
            name="DeliveryInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150)),
                ("surname", models.CharField(blank=True, max_length=150)),
                ("phone_number", models.CharField(blank=True, max_length=150)),
                ("country", models.CharField(blank=True, max_length=150)),
                ("city", models.CharField(blank=True, max_length=150)),
                ("postcode", models.CharField(blank=True, max_length=150)),
                ("address", models.CharField(blank=True, max_length=150)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
