# Generated by Django 4.1.3 on 2023-02-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_rename_city_deliveryinfo_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryinfo",
            name="country",
            field=models.CharField(
                blank=True, choices=[("US", "United States")], max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="deliveryinfo",
            name="state",
            field=models.CharField(
                blank=True, choices=[("GA", "Georgia")], max_length=2
            ),
        ),
    ]
