# Generated by Django 4.1.3 on 2023-03-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_deliveryinfo_zip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbase",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="userbase",
            name="surname",
            field=models.CharField(max_length=150),
        ),
    ]
