# Generated by Django 4.1.3 on 2022-11-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="address",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
