# Generated by Django 4.1.3 on 2023-03-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_category_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="collection",
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
