# Generated by Django 4.1.3 on 2023-04-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_product_color_remove_product_quantity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productvariant",
            old_name="quantity",
            new_name="available_units",
        ),
    ]
