# Generated by Django 4.1.3 on 2022-11-25 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_users_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="images",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="users",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
