# Generated by Django 4.1.3 on 2023-03-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_remove_product_collection_category_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Collection",
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, default="default_item.png", upload_to="category_pics"
            ),
        ),
    ]
