# Generated by Django 4.1.3 on 2022-11-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_cart_user_delete_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="images",
        ),
        migrations.AddField(
            model_name="stock",
            name="image",
            field=models.ImageField(blank=True, upload_to="stock_pics"),
        ),
    ]
