# Generated by Django 4.1.3 on 2023-03-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_delete_collection_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="promo",
            field=models.BooleanField(default=False),
        ),
    ]
