# Generated by Django 4.1.3 on 2023-04-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_options_alter_productvariant_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="image",
            field=models.ImageField(
                blank=True,
                default="/product_pics/default_item.png",
                upload_to="product_pics",
            ),
        ),
    ]
