# Generated by Django 4.1.3 on 2023-03-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_product_promo"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="material",
            field=models.CharField(default="leather", max_length=255),
            preserve_default=False,
        ),
    ]
