# Generated by Django 4.1.3 on 2022-11-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_remove_stock_images_stock_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="image",
            field=models.ImageField(
                blank=True, default="default_item.png", upload_to="stock_pics"
            ),
        ),
    ]
