# Generated by Django 4.1.3 on 2023-04-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_productvariant_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="/product_pics/default_item.png",
                upload_to="product_pics",
            ),
        ),
    ]
