# Generated by Django 4.1.3 on 2023-04-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="new",
        ),
        migrations.RemoveField(
            model_name="product",
            name="promo",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sale",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="new",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="promo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="sale",
            field=models.BooleanField(default=False),
        ),
    ]
