# Generated by Django 4.1.3 on 2022-11-30 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_stock_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
