# Generated by Django 4.1.3 on 2023-03-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_product_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(default="black", max_length=30),
            preserve_default=False,
        ),
    ]
