# Generated by Django 4.1.3 on 2023-08-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_image_remove_product_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
