# Generated by Django 4.1.3 on 2023-03-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_material_alter_product_material"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("-date_modified",)},
        ),
        migrations.RemoveField(
            model_name="color",
            name="image",
        ),
        migrations.AddField(
            model_name="color",
            name="code",
            field=models.CharField(default="ffffff", max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
