# Generated by Django 4.1.3 on 2023-03-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sex",
            field=models.CharField(
                choices=[("Women", "Women"), ("Men", "Men")], max_length=5
            ),
        ),
    ]
