services:
    ecomm-django:
        build: .
        container_name: ecomm-django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/ecomm
        ports:
            - "8000:8000"
        depends_on:
            - ecomm-db
    ecomm-db:
        image: postgres
        container_name: ecomm-db
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ecomm-pgdata:/var/lib/postgresql/data

    stripe-cli:
        image: stripe/stripe-cli
        container_name: stripe-cli
        environment:
            - STRIPE_API_SECRET_KEY=${STRIPE_API_SECRET_KEY}
        command: "listen --api-key ${STRIPE_API_SECRET_KEY} --forward-to ecomm-django:8000/payment/webhook/"

volumes:
    ecomm-pgdata:
        
   
