# Generated by Django 4.1.3 on 2023-03-23 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.deliveryinfo"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="ordered_items",
            field=models.ManyToManyField(to="orders.ordereditem"),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
