# Generated by Django 4.1.3 on 2023-02-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_paid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("updated_at",)},
        ),
        migrations.AddField(
            model_name="order",
            name="order_key",
            field=models.CharField(default="defaultkey", max_length=200),
            preserve_default=False,
        ),
    ]
